import {
  BadgeDollarSign,
  Building2,
  Factory,
  Fence,
  Handshake,
  Home,
  KeyRound,
  LandPlot,
  MapPinned,
  ShieldCheck,
  Store,
  Trees,
  Warehouse,
} from "lucide-react";

export const listingTypeOptions = [
  {
    value: "sale",
    label: "For sale",
    description: "Residential or land listings for buyers.",
    icon: BadgeDollarSign,
  },
  {
    value: "rental",
    label: "Rental",
    description: "Monthly rental homes, apartments, and commercial spaces.",
    icon: KeyRound,
  },
  {
    value: "development",
    label: "Development",
    description: "New developments, projects, and available units.",
    icon: Building2,
  },
  {
    value: "commercial",
    label: "Commercial",
    description: "Office, retail, industrial, and mixed-use opportunities.",
    icon: Store,
  },
] as const;

export const propertyCategoryOptions = [
  {
    value: "residential",
    label: "Residential",
    description: "Homes, apartments, townhouses, estates, and lifestyle homes.",
    icon: Home,
  },
  {
    value: "commercial",
    label: "Commercial",
    description: "Offices, retail, industrial, warehouses, hospitality, and mixed use.",
    icon: Store,
  },
  {
    value: "land",
    label: "Land",
    description: "Vacant stands, development land, and agricultural land.",
    icon: LandPlot,
  },
  {
    value: "farm",
    label: "Farm / smallholding",
    description: "Farms, smallholdings, lifestyle farms, and rural properties.",
    icon: Trees,
  },
  {
    value: "development",
    label: "Development",
    description: "New projects, estate rollouts, sectional title schemes, and units.",
    icon: MapPinned,
  },
] as const;

export const propertyTypeOptions = [
  {
    value: "free_standing_house",
    label: "Free-standing house",
    category: "residential",
    listingTypes: ["sale", "rental"],
    icon: Home,
  },
  {
    value: "apartment",
    label: "Apartment / flat",
    category: "residential",
    listingTypes: ["sale", "rental", "development"],
    icon: Building2,
  },
  {
    value: "townhouse",
    label: "Townhouse",
    category: "residential",
    listingTypes: ["sale", "rental", "development"],
    icon: Home,
  },
  {
    value: "duet",
    label: "Duet",
    category: "residential",
    listingTypes: ["sale", "rental"],
    icon: Home,
  },
  {
    value: "cluster_home",
    label: "Cluster home",
    category: "residential",
    listingTypes: ["sale", "rental"],
    icon: Home,
  },
  {
    value: "estate_home",
    label: "Estate home",
    category: "residential",
    listingTypes: ["sale", "rental"],
    icon: Trees,
  },
  {
    value: "lifestyle_estate",
    label: "Lifestyle estate",
    category: "residential",
    listingTypes: ["sale", "rental", "development"],
    icon: Trees,
  },
  {
    value: "golf_estate",
    label: "Golf estate",
    category: "residential",
    listingTypes: ["sale", "rental", "development"],
    icon: LandPlot,
  },
  {
    value: "security_estate",
    label: "Security estate",
    category: "residential",
    listingTypes: ["sale", "rental", "development"],
    icon: ShieldCheck,
  },
  {
    value: "retirement_unit",
    label: "Retirement unit",
    category: "residential",
    listingTypes: ["sale", "rental"],
    icon: Building2,
  },
  {
    value: "guest_house",
    label: "Guest house",
    category: "residential",
    listingTypes: ["sale", "rental", "commercial"],
    icon: Home,
  },
  {
    value: "room",
    label: "Room",
    category: "residential",
    listingTypes: ["rental"],
    icon: Home,
  },
  {
    value: "student_accommodation",
    label: "Student accommodation",
    category: "residential",
    listingTypes: ["rental"],
    icon: Building2,
  },
  {
    value: "flatlet",
    label: "Flatlet / garden cottage",
    category: "residential",
    listingTypes: ["sale", "rental"],
    icon: Home,
  },
  {
    value: "vacant_land",
    label: "Vacant land",
    category: "land",
    listingTypes: ["sale"],
    icon: LandPlot,
  },
  {
    value: "development_land",
    label: "Development land",
    category: "land",
    listingTypes: ["sale", "development"],
    icon: LandPlot,
  },
  {
    value: "agricultural_land",
    label: "Agricultural land",
    category: "land",
    listingTypes: ["sale"],
    icon: Fence,
  },
  {
    value: "small_holding",
    label: "Smallholding",
    category: "farm",
    listingTypes: ["sale", "rental"],
    icon: Trees,
  },
  {
    value: "farm",
    label: "Farm",
    category: "farm",
    listingTypes: ["sale", "rental"],
    icon: Trees,
  },
  {
    value: "lifestyle_farm",
    label: "Lifestyle farm",
    category: "farm",
    listingTypes: ["sale", "rental"],
    icon: Trees,
  },
  {
    value: "game_farm",
    label: "Game farm",
    category: "farm",
    listingTypes: ["sale"],
    icon: Trees,
  },
  {
    value: "wine_farm",
    label: "Wine farm",
    category: "farm",
    listingTypes: ["sale"],
    icon: Trees,
  },
  {
    value: "development_project",
    label: "Development project",
    category: "development",
    listingTypes: ["development"],
    icon: MapPinned,
  },
  {
    value: "development_unit",
    label: "Development unit",
    category: "development",
    listingTypes: ["development"],
    icon: Building2,
  },
  {
    value: "sectional_title_development",
    label: "Sectional title development",
    category: "development",
    listingTypes: ["development"],
    icon: Building2,
  },
  {
    value: "estate_development",
    label: "Estate development",
    category: "development",
    listingTypes: ["development"],
    icon: Trees,
  },
  {
    value: "commercial_development",
    label: "Commercial development",
    category: "development",
    listingTypes: ["development", "commercial"],
    icon: Store,
  },
  {
    value: "commercial_property",
    label: "Commercial property",
    category: "commercial",
    listingTypes: ["commercial", "sale", "rental"],
    icon: Store,
  },
  {
    value: "office",
    label: "Office",
    category: "commercial",
    listingTypes: ["commercial", "rental", "sale"],
    icon: Building2,
  },
  {
    value: "retail",
    label: "Retail",
    category: "commercial",
    listingTypes: ["commercial", "rental", "sale"],
    icon: Store,
  },
  {
    value: "industrial",
    label: "Industrial",
    category: "commercial",
    listingTypes: ["commercial", "rental", "sale"],
    icon: Factory,
  },
  {
    value: "warehouse",
    label: "Warehouse",
    category: "commercial",
    listingTypes: ["commercial", "rental", "sale"],
    icon: Warehouse,
  },
  {
    value: "factory",
    label: "Factory",
    category: "commercial",
    listingTypes: ["commercial", "rental", "sale"],
    icon: Factory,
  },
  {
    value: "showroom",
    label: "Showroom",
    category: "commercial",
    listingTypes: ["commercial", "rental", "sale"],
    icon: Store,
  },
  {
    value: "medical_suite",
    label: "Medical suite",
    category: "commercial",
    listingTypes: ["commercial", "rental", "sale"],
    icon: Building2,
  },
  {
    value: "restaurant",
    label: "Restaurant / food premises",
    category: "commercial",
    listingTypes: ["commercial", "rental", "sale"],
    icon: Store,
  },
  {
    value: "mixed_use",
    label: "Mixed use",
    category: "commercial",
    listingTypes: ["commercial", "sale", "rental"],
    icon: Building2,
  },
  {
    value: "business_premises",
    label: "Business premises",
    category: "commercial",
    listingTypes: ["commercial", "sale", "rental"],
    icon: Store,
  },
  {
    value: "hospitality",
    label: "Hospitality",
    category: "commercial",
    listingTypes: ["commercial", "sale", "rental"],
    icon: Building2,
  },
] as const;

export const mandateTypeOptions = [
  {
    value: "open",
    label: "Open mandate",
    description:
      "Multiple agents or agencies may market the property. Commission is usually earned by the agent who concludes the transaction.",
    icon: Handshake,
  },
  {
    value: "sole",
    label: "Sole mandate",
    description:
      "One agent or agency has exclusive authority to market the property for the agreed mandate period.",
    icon: ShieldCheck,
  },
  {
    value: "dual",
    label: "Dual mandate",
    description:
      "Two appointed agents or agencies may market the property under the agreed mandate terms.",
    icon: Handshake,
  },
  {
    value: "rental",
    label: "Rental mandate",
    description:
      "Authority to market and let the property, usually tied to finding and placing a tenant.",
    icon: KeyRound,
  },
  {
    value: "development",
    label: "Development mandate",
    description:
      "Used for developer or project stock where the agent is marketing units, phases, or a development portfolio.",
    icon: Building2,
  },
] as const;

export const featureOptions = [
  "Pool",
  "Garden",
  "Solar",
  "Backup power",
  "Security",
  "Fibre",
  "Sea view",
  "Mountain view",
  "Pet friendly",
  "Furnished",
  "Air conditioning",
  "Staff quarters",
] as const;

export type ListingType = (typeof listingTypeOptions)[number]["value"];
export type PropertyCategory = (typeof propertyCategoryOptions)[number]["value"];
export type PropertyType = (typeof propertyTypeOptions)[number]["value"];
export type MandateType = (typeof mandateTypeOptions)[number]["value"];
